### ISSUE TITLE
consider giving `load_sigpaths_from_zip` a template sketch?

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/pyo3_branchwater#109]
`load_sigpaths_from_zip` unpacks the zip file into a temp directory. This could take up a lot of disk space! I wonder if it might make sense to examine each sketch for compatibility with the query and only save those that are actually going to be used?

**Comment by bluegenes** [comment]
might also be worth passing a `threshold` to allow direct loading of sigs for `fastgather` as well
