### ISSUE TITLE
change license to AGPL for next release

### ISSUE THREAD

**Issue by ctb** [sourmash-bio/pyo3_branchwater#60]
since #58 includes/is based on code (https://github.com/luizirber/2022-06-26-rocksdb-eval) that is now AGPL (https://github.com/sourmash-bio/mastiff).

**Comment by bluegenes** [comment]
should I just include the mastiff AGPL license in #58? 
https://github.com/sourmash-bio/mastiff/blob/latest/LICENSE-AGPL

**Comment by ctb** [comment]
fixed by #66
